version: "3.3"

services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     - BACKEND_HOST=backend
  #     - BACKEND_PORT=4000
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  #   restart: on-failure
  #   command: ["npm", "run", "dev"]
  prisma:
    ports:
      - "4466:4466"
  backend:
    build:
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    build:
      context: ./server
      dockerfile: ./Dockerfiledev
    environment:
      NODE_ENV: development