version: "3.4"
services:
  nginx:
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "0.0.0.0:80:80"
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
